### ISSUE TITLE
Use jQuery Repository Maintainers Guide

### ISSUE THREAD

**Issue by Arkni** [Arkni/jquery-validation#2]
@staabm

I don't want to create an issue on the main repo because it's not a real issue. It's just about the repo's history, for me it looks a bit ugly (see image bellow). If the history doesn't matter, just ignore.

I don't know if you want or not, but I suggest the use of the [`jQuery Repository Maintainers Guide`](http://contribute.jquery.org/repo-maintainers-guide/) in order to merge PRs, so the history will be clean as before.

Thanks

Sorry for having disturbed you :(

----
----
![screenshot from 2015-11-04 13 18 30](https://cloud.githubusercontent.com/assets/6888059/10939038/9823fb56-82f6-11e5-8331-92219f85cadc.png)

**Comment by staabm** [comment]
I am not aware of this GUIDE, will have a look at it when time allows. thx for the heads up.

**Comment by Arkni** [comment]
Thanks :)
